/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CouponsAddRouteImport } from './routes/coupons.add'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsAddRoute = CouponsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => CouponsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coupons': typeof CouponsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/coupons/add': typeof CouponsAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coupons': typeof CouponsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/coupons/add': typeof CouponsAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coupons': typeof CouponsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/coupons/add': typeof CouponsAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coupons' | '/settings' | '/coupons/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coupons' | '/settings' | '/coupons/add'
  id: '__root__' | '/' | '/coupons' | '/settings' | '/coupons/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CouponsRoute: typeof CouponsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons/add': {
      id: '/coupons/add'
      path: '/add'
      fullPath: '/coupons/add'
      preLoaderRoute: typeof CouponsAddRouteImport
      parentRoute: typeof CouponsRoute
    }
  }
}

interface CouponsRouteChildren {
  CouponsAddRoute: typeof CouponsAddRoute
}

const CouponsRouteChildren: CouponsRouteChildren = {
  CouponsAddRoute: CouponsAddRoute,
}

const CouponsRouteWithChildren =
  CouponsRoute._addFileChildren(CouponsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CouponsRoute: CouponsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
